captainVersion: 4
caproverOneClickApp:
    displayName: Evolution API
    isOfficial: false
    description: Evolution API with MongoDB, Redis, and Mongo-Express
    documentation: https://your-documentation-link-here
    variables:
        - id: $$cap_evolution_api_version
          label: Evolution API Version
          defaultValue: local
        - id: $$cap_mongo_version
          label: MongoDB Version
          defaultValue: latest
        - id: $$cap_redis_version
          label: Redis Version
          defaultValue: latest

    instructions:
        start: Deployment is starting for Evolution API...
        end: Evolution API deployed successfully.

services:
    $$cap_appname-api:
        image: evolution/api:$$cap_evolution_api_version
        ports:
            - 8080:8080
        volumes:
            - evolution_instances:/evolution/instances
            - evolution_store:/evolution/store
        networks:
            - evolution-net
        command: ['node', './dist/src/main.js']
        environment:
            SERVER_URL: $$cap_SERVER_URL
            CORS_ORIGIN: $$cap_CORS_ORIGIN
            CORS_METHODS: $$cap_CORS_METHODS
            CORS_CREDENTIALS: $$cap_CORS_CREDENTIALS
            LOG_LEVEL: $$cap_LOG_LEVEL
            LOG_BAILEYS: $$cap_LOG_BAILEYS
            DEL_INSTANCE: $$cap_DEL_INSTANCE
            STORE_MESSAGES: $$cap_STORE_MESSAGES
            STORE_MESSAGE_UP: $$cap_STORE_MESSAGE_UP
            STORE_CONTACTS: $$cap_STORE_CONTACTS
            STORE_CHATS: $$cap_STORE_CHATS
            CLEAN_STORE_CLEANING_INTERVAL: $$cap_CLEAN_STORE_CLEANING_INTERVAL
            CLEAN_STORE_MESSAGES: $$cap_CLEAN_STORE_MESSAGES
            CLEAN_STORE_MESSAGE_UP: $$cap_CLEAN_STORE_MESSAGE_UP
            CLEAN_STORE_CONTACTS: $$cap_CLEAN_STORE_CONTACTS
            CLEAN_STORE_CHATS: $$cap_CLEAN_STORE_CHATS
            DATABASE_ENABLED: $$cap_DATABASE_ENABLED
            DATABASE_CONNECTION_URI: $$cap_DATABASE_CONNECTION_URI
            DATABASE_CONNECTION_DB_PREFIX_NAME: $$cap_DATABASE_CONNECTION_DB_PREFIX_NAME
            DATABASE_SAVE_DATA_INSTANCE: $$cap_DATABASE_SAVE_DATA_INSTANCE
            DATABASE_SAVE_DATA_NEW_MESSAGE: $$cap_DATABASE_SAVE_DATA_NEW_MESSAGE
            DATABASE_SAVE_MESSAGE_UPDATE: $$cap_DATABASE_SAVE_MESSAGE_UPDATE
            DATABASE_SAVE_DATA_CONTACTS: $$cap_DATABASE_SAVE_DATA_CONTACTS
            DATABASE_SAVE_DATA_CHATS: $$cap_DATABASE_SAVE_DATA_CHATS
            REDIS_ENABLED: $$cap_REDIS_ENABLED
            REDIS_URI: $$cap_REDIS_URI
            REDIS_PREFIX_KEY: $$cap_REDIS_PREFIX_KEY
            RABBITMQ_ENABLED: $$cap_RABBITMQ_ENABLED
            RABBITMQ_URI: $$cap_RABBITMQ_URI
            WEBSOCKET_ENABLED: $$cap_WEBSOCKET_ENABLED
            WEBHOOK_GLOBAL_URL: $$cap_WEBHOOK_GLOBAL_URL
            WEBHOOK_GLOBAL_ENABLED: $$cap_WEBHOOK_GLOBAL_ENABLED
            WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: $$cap_WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS
            WEBHOOK_EVENTS_APPLICATION_STARTUP: $$cap_WEBHOOK_EVENTS_APPLICATION_STARTUP
            WEBHOOK_EVENTS_QRCODE_UPDATED: $$cap_WEBHOOK_EVENTS_QRCODE_UPDATED
            WEBHOOK_EVENTS_MESSAGES_SET: $$cap_WEBHOOK_EVENTS_MESSAGES_SET
            WEBHOOK_EVENTS_MESSAGES_UPSERT: $$cap_WEBHOOK_EVENTS_MESSAGES_UPSERT
            WEBHOOK_EVENTS_MESSAGES_UPDATE: $$cap_WEBHOOK_EVENTS_MESSAGES_UPDATE
            WEBHOOK_EVENTS_MESSAGES_DELETE: $$cap_WEBHOOK_EVENTS_MESSAGES_DELETE
            WEBHOOK_EVENTS_SEND_MESSAGE: $$cap_WEBHOOK_EVENTS_SEND_MESSAGE
            WEBHOOK_EVENTS_CONTACTS_SET: $$cap_WEBHOOK_EVENTS_CONTACTS_SET
            WEBHOOK_EVENTS_CONTACTS_UPSERT: $$cap_WEBHOOK_EVENTS_CONTACTS_UPSERT
            WEBHOOK_EVENTS_CONTACTS_UPDATE: $$cap_WEBHOOK_EVENTS_CONTACTS_UPDATE
            WEBHOOK_EVENTS_PRESENCE_UPDATE: $$cap_WEBHOOK_EVENTS_PRESENCE_UPDATE
            WEBHOOK_EVENTS_CHATS_SET: $$cap_WEBHOOK_EVENTS_CHATS_SET
            WEBHOOK_EVENTS_CHATS_UPSERT: $$cap_WEBHOOK_EVENTS_CHATS_UPSERT
            WEBHOOK_EVENTS_CHATS_UPDATE: $$cap_WEBHOOK_EVENTS_CHATS_UPDATE
            WEBHOOK_EVENTS_CHATS_DELETE: $$cap_WEBHOOK_EVENTS_CHATS_DELETE
            WEBHOOK_EVENTS_GROUPS_UPSERT: $$cap_WEBHOOK_EVENTS_GROUPS_UPSERT
            WEBHOOK_EVENTS_GROUPS_UPDATE: $$cap_WEBHOOK_EVENTS_GROUPS_UPDATE
            WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE: $$cap_WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE
            WEBHOOK_EVENTS_CONNECTION_UPDATE: $$cap_WEBHOOK_EVENTS_CONNECTION_UPDATE
            WEBHOOK_EVENTS_CALL: $$cap_WEBHOOK_EVENTS_CALL
            WEBHOOK_EVENTS_NEW_JWT_TOKEN: $$cap_WEBHOOK_EVENTS_NEW_JWT_TOKEN
            CONFIG_SESSION_PHONE_CLIENT: $$cap_CONFIG_SESSION_PHONE_CLIENT
            CONFIG_SESSION_PHONE_NAME: $$cap_CONFIG_SESSION_PHONE_NAME
            QRCODE_LIMIT: $$cap_QRCODE_LIMIT
            QRCODE_COLOR: $$cap_QRCODE_COLOR
            AUTHENTICATION_TYPE: $$cap_AUTHENTICATION_TYPE
            AUTHENTICATION_API_KEY: $$cap_AUTHENTICATION_API_KEY
            AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: $$cap_AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES
            AUTHENTICATION_JWT_EXPIRIN_IN: $$cap_AUTHENTICATION_JWT_EXPIRIN_IN
            AUTHENTICATION_JWT_SECRET: $$cap_AUTHENTICATION_JWT_SECRET

    $$cap_appname-mongodb:
        image: mongo:$$cap_mongo_version
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - PUID=1000
            - PGID=1000
        volumes:
            - evolution_mongodb_data:/data/db
            - evolution_mongodb_configdb:/data/configdb
        networks:
            - evolution-net

    $$cap_appname-redis:
        image: redis:$$cap_redis_version
        ports:
            - 6379:6379
        command:
            - redis-server
            - --port 6379
            - --appendonly yes
        volumes:
            - evolution_redis:/data
        networks:
            - evolution-net

    $$cap_appname-mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_BASICAUTH_USERNAME=root
            - ME_CONFIG_BASICAUTH_PASSWORD=root
            - ME_CONFIG_MONGODB_SERVER=$$cap_appname-mongodb
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
        networks:
            - evolution-net

volumes:
    evolution_instances:
    evolution_store:
    evolution_mongodb_data:
    evolution_mongodb_configdb:
    evolution_redis:

networks:
    evolution-net:
        driver: bridge
