captainVersion: 4
services:
    $$cap_appname-db:
        image: mysql:5.7
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: helper
            MYSQL_USER: helper
            MYSQL_PASSWORD: $$cap_db_password
            MYSQL_ROOT_PASSWORD: $$cap_db_root_password
        restart: always
        caproverExtra:
            containerHttpPort: '3306'
            notExposeAsWebApp: true

    $$cap_appname-helper:
        image: eloufirhatim/helper:$$cap_helper_version
        volumes:
            - /etc/localtime:/etc/localtime
        environment:
            DB_CONNECTION: mysql
            DB_HOST: srv-captain--$$cap_appname-db
            DB_PORT: 3306
            DB_DATABASE: helper
            DB_USERNAME: helper
            DB_PASSWORD: $$cap_db_password
            MAIL_MAILER: smtp
            MAIL_HOST: post.uhlhosting.ch
            MAIL_PORT: 25
            MAIL_USERNAME: $$cap_mail_username
            MAIL_PASSWORD: $$cap_mail_password
            MAIL_ENCRYPTION: tls
        depends_on:
            - $$cap_appname-db
        restart: always
        caproverExtra:
            containerHttpPort: '8000'
            notExposeAsWebApp: false
            websocketSupport: 'true'

caproverOneClickApp:
    variables:
        - id: $$cap_db_password
          label: Database User Password
          defaultValue: helper
          description: Password for the database user 'helper'.
          validRegex: /^.{1,}$/

        - id: $$cap_db_root_password
          label: Database Root Password
          defaultValue: helper
          description: Root password for the MySQL database. It's recommended to change this!
          validRegex: /^.{1,}$/

        - id: $$cap_helper_version
          label: Helper Application Version
          defaultValue: latest
          description: The Docker image version of the helper application.
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_mail_username
          label: Mail Username
          defaultValue: your_username
          description: Username for the mail service.

        - id: $$cap_mail_password
          label: Mail Password
          defaultValue: your_password
          description: Password for the mail service.

    instructions:
        start: >-
            This template sets up a MySQL database and a custom helper application. Ensure you have the correct database and mail configuration before proceeding.
        end: >-
            Your applications are now deployed. Please check the application dashboard for more details.
    displayName: Custom Application with MySQL Database
    isOfficial: false
    description: This template deploys a custom application alongside a MySQL database, with integrated mail support.
    documentation: Please refer to the official Docker images for MySQL and your application for further configuration options and best practices.
