captainVersion: 4
services:
    # Frontend Service
    $$cap_appname-frontend:
        image: daveearley/hi.events-frontend:$$cap_app_version
        restart: always
        environment:
            VITE_FRONTEND_URL: /
            VITE_API_URL_CLIENT: /api
            VITE_API_URL_SERVER: /api
            VITE_STRIPE_PUBLISHABLE_KEY: $$cap_stripe_publishable_key
        depends_on:
            - $$cap_appname-backend
        caproverExtra:
            containerHttpPort: 5678

    # Backend Service
    $$cap_appname-backend:
        image: daveearley/hi.events-backend:$$cap_app_version
        restart: always
        environment:
            APP_KEY: $$cap_app_key
            APP_FRONTEND_URL: http://$$cap_appname-frontend.$$cap_root_domain
            DB_CONNECTION: pgsql
            DB_HOST: srv-captain--$$cap_appname-db
            DB_PORT: 5432
            DB_DATABASE: hi_events
            DB_USERNAME: hi_events
            DB_PASSWORD: $$cap_db_password
            REDIS_HOST: srv-captain--$$cap_appname-redis
            REDIS_PORT: 6379
            QUEUE_CONNECTION: redis
            FILESYSTEM_PUBLIC_DISK: public
            FILESYSTEM_PRIVATE_DISK: private
            LOG_CHANNEL: stderr
            JWT_SECRET: $$cap_jwt_secret
            STRIPE_PUBLIC_KEY: $$cap_stripe_public_key
            STRIPE_SECRET_KEY: $$cap_stripe_secret_key
            STRIPE_WEBHOOK_SECRET: $$cap_stripe_webhook_secret
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
        caproverExtra:
            notExposeAsWebApp: 'true'

    # Database Service (PostgreSQL)
    $$cap_appname-db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: hi_events
            POSTGRES_PASSWORD: $$cap_db_password
            POSTGRES_DB: hi_events
        volumes:
            - $$cap_appname-db:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'

    # Redis Service
    $$cap_appname-redis:
        image: redis:7
        restart: always
        volumes:
            - $$cap_appname-redis:/data
        caproverExtra:
            notExposeAsWebApp: 'true'

caproverOneClickApp:
    variables:
        - id: $$cap_app_version
          label: hi.events Version
          defaultValue: latest
          description: The version of hi.events to deploy (e.g., latest).

        - id: $$cap_stripe_publishable_key
          label: Stripe Publishable Key
          description: Your Stripe publishable key (e.g., pk_test_51...).

        - id: $$cap_jwt_secret
          label: JWT Secret
          defaultValue: $$cap_gen_random_hex(256)
          description: Application key (generate using `openssl rand -base64 256`.

        - id: $$cap_stripe_public_key
          label: Stripe Public Key
          description: Your Stripe public key (e.g., pk_test_51...).

        - id: $$cap_stripe_secret_key
          label: Stripe Secret Key
          description: Your Stripe secret key (e.g., sk_test_51...).

        - id: $$cap_stripe_webhook_secret
          label: Stripe Webhook Secret
          description: Your Stripe webhook secret (e.g., whsec_...).

        - id: $$cap_app_key
          label: App Key
          defaultValue: $$cap_gen_random_hex(32)
          description: Application key (generate using `openssl rand -base64 32`).

        - id: $$cap_db_password
          label: Database Password
          defaultValue: $$cap_gen_random_hex(16)
          description: Database password for PostgreSQL.

    instructions:
        start: >-
            hi.events is a modern event management platform. This one-click app will deploy the frontend and backend as separate services for better scalability.
        end: >-
            Done! 😄
            Your hi.events service is available at [http://$$cap_appname-frontend.$$cap_root_domain](http://$$cap_appname-frontend.$$cap_root_domain).
            Make sure to configure your Stripe webhook at [https://dashboard.stripe.com/webhooks](https://dashboard.stripe.com/webhooks) with the URL: [http://$$cap_appname-frontend.$$cap_root_domain/api/webhooks/stripe](http://$$cap_appname-frontend.$$cap_root_domain/api/webhooks/stripe).
    displayName: 'hi.events (Separate Services)'
    isOfficial: false
    description: A modern event management platform. Deploy the frontend and backend as separate services for better scalability.
    documentation: https://github.com/daveearley/hi.events
