captainVersion: 4
services:
    hi-events-frontend:
        image: daveearley/hi.events-frontend
        environment:
            VITE_FRONTEND_URL: $$cap_frontend_url
            VITE_API_URL_CLIENT: $$cap_api_url_client
            VITE_API_URL_SERVER: $$cap_api_url_server
            VITE_STRIPE_PUBLISHABLE_KEY: $$cap_stripe_publishable_key
        caproverExtra:
            containerHttpPort: '80'
        restart: always

    hi-events-backend:
        image: daveearley/hi.events-backend
        environment:
            # Mail Configuration
            MAIL_MAILER: $$cap_mail_mailer
            MAIL_HOST: $$cap_mail_host
            MAIL_PORT: $$cap_mail_port
            MAIL_USERNAME: $$cap_mail_username
            MAIL_PASSWORD: $$cap_mail_password
            MAIL_FROM_ADDRESS: $$cap_mail_from_address
            MAIL_FROM_NAME: $$cap_mail_from_name

            # Stripe Configuration
            STRIPE_PUBLIC_KEY: $$cap_stripe_public_key
            STRIPE_SECRET_KEY: $$cap_stripe_secret_key
            STRIPE_WEBHOOK_SECRET: $$cap_stripe_webhook_secret

            # General Application Configuration
            APP_KEY: $$cap_app_key
            APP_SAAS_MODE_ENABLED: $$cap_app_saas_mode_enabled
            APP_SAAS_STRIPE_APPLICATION_FEE_PERCENT: $$cap_app_saas_stripe_application_fee_percent
            APP_FRONTEND_URL: $$cap_app_frontend_url
            APP_CDN_URL: $$cap_app_cdn_url
            APP_DISABLE_REGISTRATION: $$cap_app_disable_registration
            FILESYSTEM_PUBLIC_DISK: $$cap_filesystem_public_disk
            FILESYSTEM_PRIVATE_DISK: $$cap_filesystem_private_disk
            JWT_SECRET: $$cap_jwt_secret
            LOG_CHANNEL: $$cap_log_channel

            # AWS Configuration
            AWS_ACCESS_KEY_ID: $$cap_aws_access_key_id
            AWS_SECRET_ACCESS_KEY: $$cap_aws_secret_access_key
            AWS_DEFAULT_REGION: $$cap_aws_default_region
            AWS_PUBLIC_BUCKET: $$cap_aws_public_bucket
            AWS_PRIVATE_BUCKET: $$cap_aws_private_bucket

            # Database Configuration (Hardcoded)
            DB_CONNECTION: 'pgsql'
            DB_HOST: 'srv-captain--hi-events-db'
            DB_PORT: '5432'
            DB_DATABASE: 'hi_events_db'
            DB_USERNAME: 'hi_events_user'
            DB_PASSWORD: 'hi_events_password'
            DATABASE_URL: 'postgres://hi_events_user:hi_events_password@srv-captain--hi-events-db:5432/hi_events_db'

            # Redis Configuration (Hardcoded)
            REDIS_HOST: 'srv-captain--hi-events-redis'
            REDIS_USER: 'default'
            REDIS_PASSWORD: 'redis_password'
            REDIS_PORT: '6379'
            REDIS_URL: 'redis://default:redis_password@srv-captain--hi-events-redis:6379'

            # Queue Configuration
            QUEUE_CONNECTION: $$cap_queue_connection
        caproverExtra:
            containerHttpPort: '8000'
        restart: always

    hi-events-db:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: 'hi_events_db'
            POSTGRES_USER: 'hi_events_user'
            POSTGRES_PASSWORD: 'hi_events_password'
        volumes:
            - hi-events-db-data:/var/lib/postgresql/data
        caproverExtra:
            containerHttpPort: '5432'
            notExposeAsWebApp: 'true'
        restart: always

    hi-events-redis:
        image: redis:6-alpine
        environment: {}
        volumes:
            - hi-events-redis-data:/data
        caproverExtra:
            containerHttpPort: '6379'
            notExposeAsWebApp: 'true'
        restart: always

volumes:
    hi-events-db-data:
    hi-events-redis-data:

caproverOneClickApp:
    variables:
        # Frontend Variables
        - id: $$cap_frontend_url
          label: VITE_FRONTEND_URL
          defaultValue: 'https://your-app.com'
          description: 'Frontend URL.'
          validRegex: /^https?:\/\/.*$/
        - id: $$cap_api_url_client
          label: VITE_API_URL_CLIENT
          defaultValue: 'https://your-app.com/api'
          description: 'API URL for use in the browser.'
          validRegex: /^https?:\/\/.*$/
        - id: $$cap_api_url_server
          label: VITE_API_URL_SERVER
          defaultValue: 'https://your-app.com/api'
          description: 'API URL for use on the server.'
          validRegex: /^https?:\/\/.*$/
        - id: $$cap_stripe_publishable_key
          label: VITE_STRIPE_PUBLISHABLE_KEY
          defaultValue: 'pk_test_51...'
          description: 'Stripe publishable key for the frontend.'
          validRegex: /^pk_[a-zA-Z0-9_]+$/

        # Backend Mail Variables
        - id: $$cap_mail_mailer
          label: MAIL_MAILER
          defaultValue: 'smtp'
          description: 'Mail driver to be used.'
          validRegex: /^smtp$/
        - id: $$cap_mail_host
          label: MAIL_HOST
          defaultValue: 'smtp.mailtrap.io'
          description: 'Mail server host.'
          validRegex: /^.*$/
        - id: $$cap_mail_port
          label: MAIL_PORT
          defaultValue: '2525'
          description: 'Mail server port.'
          validRegex: /^[0-9]+$/
        - id: $$cap_mail_username
          label: MAIL_USERNAME
          defaultValue: 'your-username'
          description: 'Mail server username.'
          validRegex: /^.*$/
        - id: $$cap_mail_password
          label: MAIL_PASSWORD
          defaultValue: 'your-password'
          description: 'Mail server password.'
          validRegex: /^.*$/
        - id: $$cap_mail_from_address
          label: MAIL_FROM_ADDRESS
          defaultValue: 'me@mywebsite.com'
          description: 'Mail from address.'
          validRegex: /^.*@.*$/
        - id: $$cap_mail_from_name
          label: MAIL_FROM_NAME
          defaultValue: 'Your App Name'
          description: 'Mail from name.'
          validRegex: /^.*$/

        # Backend Stripe Variables
        - id: $$cap_stripe_public_key
          label: STRIPE_PUBLIC_KEY
          defaultValue: 'pk_test_51...'
          description: 'Stripe public key.'
          validRegex: /^pk_[a-zA-Z0-9_]+$/
        - id: $$cap_stripe_secret_key
          label: STRIPE_SECRET_KEY
          defaultValue: 'sk_test_51...'
          description: 'Stripe secret key.'
          validRegex: /^sk_[a-zA-Z0-9_]+$/
        - id: $$cap_stripe_webhook_secret
          label: STRIPE_WEBHOOK_SECRET
          defaultValue: 'whsec_...'
          description: 'Stripe webhook secret.'
          validRegex: /^whsec_[a-zA-Z0-9_]+$/

        # General Backend Configuration Variables
        - id: $$cap_app_key
          label: APP_KEY
          defaultValue: 'base64:$$cap_gen_random_hex(64)'
          description: 'Application key generated using cap_gen_random_hex. Must be unique.'
          validRegex: /^base64:.*$/
        - id: $$cap_app_saas_mode_enabled
          label: APP_SAAS_MODE_ENABLED
          defaultValue: 'true'
          description: 'Enable SaaS mode.'
          validRegex: /^(true|false)$/
        - id: $$cap_app_saas_stripe_application_fee_percent
          label: APP_SAAS_STRIPE_APPLICATION_FEE_PERCENT
          defaultValue: '1.5'
          description: 'Stripe application fee percentage.'
          validRegex: /^[0-9]+(\.[0-9]+)?$/
        - id: $$cap_app_frontend_url
          label: APP_FRONTEND_URL
          defaultValue: 'https://your-app.com'
          description: 'Frontend URL for backend configuration.'
          validRegex: /^https?:\/\/.*$/
        - id: $$cap_app_cdn_url
          label: APP_CDN_URL
          defaultValue: 'https://cdn.your-app.com'
          description: 'CDN URL.'
          validRegex: /^https?:\/\/.*$/
        - id: $$cap_app_disable_registration
          label: APP_DISABLE_REGISTRATION
          defaultValue: 'false'
          description: 'Disable user registration.'
          validRegex: /^(true|false)$/
        - id: $$cap_filesystem_public_disk
          label: FILESYSTEM_PUBLIC_DISK
          defaultValue: 's3-public'
          description: 'Public filesystem disk.'
          validRegex: /^.*$/
        - id: $$cap_filesystem_private_disk
          label: FILESYSTEM_PRIVATE_DISK
          defaultValue: 's3-private'
          description: 'Private filesystem disk.'
          validRegex: /^.*$/
        - id: $$cap_jwt_secret
          label: JWT_SECRET
          defaultValue: 'base64:$$cap_gen_random_hex(64)'
          description: 'JWT secret key generated using cap_gen_random_hex.'
          validRegex: /^base64:.*$/
        - id: $$cap_log_channel
          label: LOG_CHANNEL
          defaultValue: 'stderr'
          description: 'Log channel.'
          validRegex: /^.*$/

        # AWS Configuration Variables
        - id: $$cap_aws_access_key_id
          label: AWS_ACCESS_KEY_ID
          defaultValue: 'your-access-key-id'
          description: 'AWS access key ID.'
          validRegex: /^.*$/
        - id: $$cap_aws_secret_access_key
          label: AWS_SECRET_ACCESS_KEY
          defaultValue: 'your-secret-access-key'
          description: 'AWS secret access key.'
          validRegex: /^.*$/
        - id: $$cap_aws_default_region
          label: AWS_DEFAULT_REGION
          defaultValue: 'us-west-1'
          description: 'AWS region.'
          validRegex: /^.*$/
        - id: $$cap_aws_public_bucket
          label: AWS_PUBLIC_BUCKET
          defaultValue: 'your-public-bucket'
          description: 'AWS public bucket name.'
          validRegex: /^.*$/
        - id: $$cap_aws_private_bucket
          label: AWS_PRIVATE_BUCKET
          defaultValue: 'your-private-bucket'
          description: 'AWS private bucket name.'
          validRegex: /^.*$/

        # Queue Configuration Variable
        - id: $$cap_queue_connection
          label: QUEUE_CONNECTION
          defaultValue: 'redis'
          description: 'Queue connection type (redis for production deployments).'
          validRegex: /^.*$/

    instructions:
        start: 'Deploying hi.events with separate frontend and backend services along with PostgreSQL and Redis.'
        end: 'Deployment complete. Access your services via the provided URLs.'
    displayName: 'hi.events Production'
    isOfficial: false
    description: 'Deploy hi.events with production-grade services for frontend and backend, integrated with PostgreSQL and Redis.'
    documentation: 'https://hi.events/docs/getting-started/deploying'
