captainVersion: 4
services:
    $$cap_appname:
        depends_on:
            - $$cap_appname-redis
        restart: on-failure
        image: 'ghcr.io/getmetal/motorhead:latest'
        environment:
            PORT: 8080
            MOTORHEAD_MAX_WINDOW_SIZE: 25
            MOTORHEAD_LONG_TERM_MEMORY: 'true'
            MOTORHEAD_MODEL: 'gpt-3.5-turbo'
            REDIS_URL: 'redis://srv-captain--$$cap_appname-redis:6379'
            OPENAI_API_KEY: $$cap_openai_api_key
        caproverExtra:
            containerHttpPort: '8080'
            websocketSupport: true

    $$cap_appname-redis:
        restart: on-failure
        image: 'redis/redis-stack-server:latest'
        volumes:
            - $$cap_appname-redis-data:/data
        caproverExtra:
            notExposeAsWebApp: true

caproverOneClickApp:
    variables:
        - id: $$cap_openai_api_key
          label: OpenAI API Key
          description: 'Your OpenAI API key.'
    instructions:
        start: 'Motörhead is starting along with Redis.'
        end: 'Motörhead and Redis have been deployed.'
    displayName: 'Motörhead'
    isOfficial: true
    description: '🧠 Motörhead is a memory and information retrieval server for LLMs.'
    documentation: 'https://getmetal.io/'
