---
captainVersion: 4
services:
    $$cap_appname-redis:
        caproverExtra:
            notExposeAsWebApp: 'true'
            dockerfileLines:
                - FROM redis:$$cap_redis_version
                - CMD redis-server --save
        volumes:
            - $$cap_appname-cache:/data
    $$cap_appname-postgres:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: weblate
            POSTGRES_PASSWORD: $$cap_pg_pass
            POSTGRES_DB: weblate
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        image: weblate/weblate:$$cap_weblate_version
        depends_on:
            - $$cap_appname-postgres
            - $$cap_appname-redis
        volumes:
            - $$cap_appname-data:/app/data
        restart: always
        environment:
            CLIENT_MAX_BODY_SIZE: 256M
            DJANGO_SETTINGS_MODULE: weblate.settings_docker
            POSTGRES_DATABASE: weblate
            POSTGRES_HOST: srv-captain--$$cap_appname-postgres
            POSTGRES_PASSWORD: $$cap_pg_pass
            POSTGRES_PORT: 5432
            POSTGRES_USER: weblate
            REDIS_HOST: srv-captain--$$cap_appname-redis
            REDIS_PORT: 6379
            SECURE_SSL_REDIRECT: $$cap_secure_ssl_redirect
            SENTRY_DSN: $$cap_sentry_dsn
            SENTRY_PROFILES_SAMPLE_RATE: $$cap_sentry_profiles_sample_rate
            SENTRY_TRACES_SAMPLE_RATE: $$cap_sentry_traces_sample_rate
            SESSION_COOKIE_SECURE: $$cap_session_cookie_secure
            WEBLATE_ADMIN_EMAIL: $$cap_weblate_admin_email
            WEBLATE_ADMIN_NAME: $$cap_weblate_admin_name
            WEBLATE_ADMIN_PASSWORD: $$cap_weblate_admin_password
            WEBLATE_ALLOWED_HOSTS: $$cap_weblate_allowed_hosts
            WEBLATE_DEBUG: $$cap_weblate_debug
            WEBLATE_DEFAULT_FROM_EMAIL: $$cap_weblate_default_from_email
            WEBLATE_EMAIL_HOST_PASSWORD: $$cap_weblate_email_host_password
            WEBLATE_EMAIL_HOST_USER: $$cap_weblate_email_host_user
            WEBLATE_EMAIL_HOST: $$cap_weblate_email_host
            WEBLATE_EMAIL_PORT: $$cap_weblate_email_port
            WEBLATE_EMAIL_USE_SSL: $$cap_weblate_email_use_ssl
            WEBLATE_EMAIL_USE_TLS: $$cap_weblate_email_use_tls
            WEBLATE_ENABLE_HTTPS: $$cap_weblate_enable_https
            WEBLATE_LOGLEVEL: $$cap_weblate_loglevel
            WEBLATE_REGISTRATION_OPEN: $$cap_weblate_registration_open
            WEBLATE_SERVER_EMAIL: $$cap_weblate_server_email
            WEBLATE_SITE_DOMAIN: $$cap_appname.$$cap_root_domain
            WEBLATE_SITE_TITLE: $$cap_weblate_site_title
            WEBLATE_TIME_ZONE: $$cap_weblate_timezone
            # Social Auth variables
            WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: $$cap_weblate_social_auth_google_oauth2_key
            WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: $$cap_weblate_social_auth_google_oauth2_secret
        caproverExtra:
            containerHttpPort: '8080'
            websocketSupport: 'true'
caproverOneClickApp:
    displayName: Weblate
    description: Open-Source Translation Management System
    isOfficial: true
    documentation: https://docs.weblate.org/
    instructions:
        start: |-
            Weblate is a free and open-source translation management system that simplifies the process of translating software, documentation, and other text assets.
            With Weblate, you can collaborate with a community of translators, automate translation workflows, and integrate with other tools like version control systems.
        end: |-
            Weblate has been successfully deployed! It may take a few moments before it's fully started.
            You can access the application at `http://$$cap_appname.$$cap_root_domain`.
            Find the administrator login details in the logs.
            If you enabled HTTPS, you should adjust the `WEBLATE_SITE_DOMAIN` environment variable accordingly.
    variables:
        - id: $$cap_postgres_version
          label: Postgres Docker version
          defaultValue: 16-alpine
          description: Check out their Docker page for the valid versions https://hub.docker.com/r/library/postgres/tags
        - id: $$cap_redis_version
          label: Redis Docker version
          defaultValue: 7-alpine
          description: Check out their Docker page for the valid versions https://hub.docker.com/r/library/redis/tags
        - id: $$cap_weblate_version
          label: weblate Docker Image tag
          defaultValue: latest
          description: latest, edge, bleeding, or version - Check out their Docker page for the valid tags https://hub.docker.com/r/weblate/weblate/tags
        - id: $$cap_pg_pass
          label: Postgres Password
          description: Password must be at least 30 characters.  Please use a random string.
          defaultValue: $$cap_gen_random_hex(30)
          validRegex: /^[^\@]{30,}$/
        - id: $$cap_weblate_loglevel
          label: Weblate Log Level
          defaultValue: 'INFO'
          description: Log level for Weblate. Choose among 'DEBUG', 'INFO', 'WARNING', 'ERROR', and 'CRITICAL'.
          validRegex: /^(DEBUG|INFO|WARNING|ERROR|CRITICAL)$/
        - id: $$cap_weblate_registration_open
          label: Weblate Open Registration
          defaultValue: '0'
          description: Allow open registration on Weblate. Use 1 for yes and 0 for no.
          validRegex: /^[01]$/
        - id: $$cap_weblate_server_email
          label: Weblate Server Email
          description: Server email address for Weblate. Used for sending system emails.
          validRegex: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/
        - id: $$cap_secure_ssl_redirect
          label: Secure SSL Redirect
          defaultValue: 'True'
          description: Enable or disable SSL redirect.
        - id: $$cap_sentry_dsn
          label: Sentry DSN
          description: Data Source Name for Sentry error tracking.
        - id: $$cap_sentry_profiles_sample_rate
          label: Sentry Profiles Sample Rate
          defaultValue: '1'
          description: Sampling rate for Sentry profiles.
        - id: $$cap_sentry_traces_sample_rate
          label: Sentry Traces Sample Rate
          defaultValue: '1'
          description: Sampling rate for Sentry traces.
        - id: $$cap_session_cookie_secure
          label: Session Cookie Secure Flag
          defaultValue: 'True'
          description: Enable or disable secure session cookies.
        - id: $$cap_weblate_admin_email
          label: Weblate Admin Email
          description: Email address of the Weblate admin.
        - id: $$cap_weblate_admin_name
          label: Weblate Admin Name
          defaultValue: 'Viorel-Cosmin Miron'
          description: Name of the Weblate admin.
        - id: $$cap_weblate_admin_password
          label: Weblate Admin Password
          description: Password for the Weblate admin.
        - id: $$cap_weblate_allowed_hosts
          label: Weblate Allowed Hosts
          defaultValue: '*'
          description: Allowed hosts for Weblate.
        - id: $$cap_weblate_debug
          label: Weblate Debug Mode
          defaultValue: '0'
          description: Debug mode for Weblate.
        - id: $$cap_weblate_default_from_email
          label: Weblate Default From Email
          defaultValue: 'loc@uhl.cloud'
          description: Default 'From' email address for Weblate.
        - id: $$cap_weblate_email_host_password
          label: Weblate Email Host Password
          description: Password for the Weblate email host.
        - id: $$cap_weblate_email_host_user
          label: Weblate Email Host User
          description: Username for the Weblate email host.
        - id: $$cap_weblate_email_host
          label: Weblate Email Host
          defaultValue: 'post.uhlhosting.ch'
          description: Host for Weblate email.
        - id: $$cap_weblate_email_port
          label: Weblate Email Port
          defaultValue: '25'
          description: Port for the Weblate email host.
        - id: $$cap_weblate_email_use_ssl
          label: Weblate Email Use SSL
          defaultValue: '0'
          description: Use SSL for Weblate email.
        - id: $$cap_weblate_email_use_tls
          label: Weblate Email Use TLS
          defaultValue: '1'
          description: Use TLS for Weblate email.
        - id: $$cap_weblate_enable_https
          label: Weblate Enable HTTPS
          defaultValue: '1'
          description: Enable HTTPS for Weblate.
        - id: $$cap_weblate_timezone
          label: Weblate Time Zone
          defaultValue: 'Europe/Prague'
          description: Time zone for Weblate.
        - id: $$cap_weblate_social_auth_google_oauth2_key
          label: Weblate Google OAuth2 Key
          description: Google OAuth2 Key for Weblate social authentication.
        - id: $$cap_weblate_social_auth_google_oauth2_secret
          label: Weblate Google OAuth2 Secret
          description: Google OAuth2 Secret for Weblate social authentication.
        - id: $$cap_weblate_social_auth_github_key
          label: Weblate GitHub OAuth Key
          description: GitHub OAuth Key for Weblate social authentication.
        - id: $$cap_weblate_social_auth_github_secret
          label: Weblate GitHub OAuth Secret
          description: GitHub OAuth Secret for Weblate social authentication.
        - id: $$cap_weblate_social_auth_facebook_key
          label: Weblate Facebook OAuth Key
          description: Facebook OAuth Key for Weblate social authentication.
        - id: $$cap_weblate_social_auth_facebook_secret
          label: Weblate Facebook OAuth Secret
          description: Facebook OAuth Secret for Weblate social authentication.
        - id: $$cap_weblate_social_auth_bitbucket_key
          label: Weblate Bitbucket OAuth Key
          description: Bitbucket OAuth Key for Weblate social authentication.
        - id: $$cap_weblate_social_auth_bitbucket_secret
          label: Weblate Bitbucket OAuth Secret
          description: Bitbucket OAuth Secret for Weblate social authentication.
        - id: $$cap_weblate_gitlab_host
          label: Weblate GitLab Host
          description: GitLab Host for Weblate integration.
        - id: $$cap_weblate_gitlab_token
          label: Weblate GitLab Token
          description: GitLab Token for Weblate integration.
        - id: $$cap_weblate_gitlab_username
          label: Weblate GitLab Username
          description: GitLab Username for Weblate integration.
